version: "2"
checks:
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 7
  method-count:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 50
  similar-code:
    enabled: false